sequenceDiagram

title 0.5: Single page app diagram

participant browser
participant server

note left of browser: The user opened the website

browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate server
    server-->>browser: HTML document
    deactivate server

browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    Note right of browser: The browser started executing the JavaScript code that fetches the JSON from the server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{content: "", date: "2025-08-06T18:21:18.806Z"}, {content: "", date: "2025-08-06T18:21:21.065Z"},…]
    deactivate server

    Note right of browser: The browser executed the callback function that renders the notes


